# -*- coding: utf-8 -*-
"""pyhton-with-youssef.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/GossipCoco/346daad4f6ec5f3db249da624e361c96/pyhton-with-youssef.ipynb
"""


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)
print(df.head())

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)
print(df.head())

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)
print(df.head())

plt.figure(figsize=(10, 6))
sns.histplot(df['Budget'], kde=True)
plt.title('Histogramme de la Colonne Budget')
plt.xlabel('Valeur de chaque ventes')
plt.ylabel('Budget en Euro')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['Budget'], kde=True, color='pink')
plt.title('Histogramme de la Colonne Budget')
plt.xlabel('Valeur de chaque vente')
plt.ylabel('Budget en Euro')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['Budget'], kde=False, color='pink')
plt.title('Histogramme de la Colonne Budget')
plt.xlabel('Valeur de chaque vente')
plt.ylabel('Budget en Euro')
plt.grid(True)  # Ajout du quadrillage
plt.show()

plt.figure(figsize=(20, 8))
sns.histplot(df['Budget'], kde=True, color='#FF6998', binwidth=250)  # Ajustez binwidth selon vos données
plt.title('Histogramme de la Colonne Budget')
plt.xlabel('Valeur de chaque vente')
plt.ylabel('Budget en Euro')
plt.grid(True)  # Ajout du quadrillage
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='IdProduit', y='Budget', data=df, color='#FF6998')
plt.title('Boxplot du Budget par IdProduit vendu')
plt.xlabel('IdProduit vendu')
plt.ylabel('Budget')
plt.show()

uploaded = files.upload()