# -*- coding: utf-8 -*-
"""Python2_with_youssef.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1Qggz4uTAdCJN_UBbNkGIkRU2Ear_Cf
"""



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)
print(df.head())

# Afficher les premières lignes du dataframe
print(df.head())

# Étape 6: Nettoyer le dataframe
# Suppression des lignes complètement vides
df.dropna(how='all', inplace=True)

# Suppression des colonnes complètement vides
df.dropna(axis=1, how='all', inplace=True)

# Suppression des colonnes non nommées
df.columns = df.iloc[0]  # Utiliser la première ligne comme en-tête de colonne
df = df[1:]  # Supprimer la première ligne maintenant devenue en-tête

# Réinitialisation de l'index
df.reset_index(drop=True, inplace=True)

# Étape 7: Afficher les premières lignes du dataframe après nettoyage
print("Après le nettoyage :")
print(df.head())
# Étape 8: Vérification de la distribution ... par Youssef EL MOUTEE

# Étape 8: Vérification de la distribution des catégories
print("Distribution des catégories de produits :")
print(df['Catégories Produit'].value_counts())

# Visualisation : Bar Plot des Sous-Catégories
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='IdSousCatégorieProduit', palette='viridis')
plt.title('Nombre de Produits par Sous-Catégorie')
plt.xlabel('Id Sous-Catégorie Produit')
plt.ylabel('Nombre de Produits')
plt.xticks(rotation=45)
plt.show()
# Visualisation 2: Box Plot des Prix par So... par Youssef EL MOUTEE

# Visualisation 2: Box Plot des Prix par Sous-Catégorie de Produit
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x='IdSousCatégorieProduit', y='Prix', palette='viridis')
plt.title('Distribution des Prix par Sous-Catégorie de Produit')
plt.xlabel('Id Sous-Catégorie Produit')
plt.ylabel('Prix')
plt.xticks(rotation=45)
plt.show()